version: '3.5'

services:
  postgres:
    container_name: db
    image: postgres:11.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"

  dozzle:
    container_name: log_monitor
    restart: unless-stopped
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


volumes:
  postgres:
  pgadmin:
  redis-data:
